export enum ConfigEnum {
  DB_USERNAME = 'DB_USERNAME',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DB_TYPE = 'DB_TYPE',
  DB_SYN = 'DB_SYN',

  LOG_ON = 'LOG_ON',
  LOG_LEVEL = 'LOG_LEVEL',
  NODE_ENV = 'NODE_ENV',
}
